logging.pattern.console: ${CONSOLE_LOG_PATTERN:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %cyan(%msg%n)}

# ===============================
# DATASOURCE
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5433/mydb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=myuser
spring.datasource.password=mypassword

# ===============================
# SQL INIT
# ===============================
spring.sql.init.mode=never

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update

# Hibernate properties
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true

#Run Configuration for docker Container : -Duser.timezone=Asia/Kolkata
#Docker command postgres:
#docker run --name postgres -e POSTGRES_USER=myuser -e POSTGRES_PASSWORD=mypassword -e POSTGRES_DB=mydb -p 5433:5432 -d postgres
#delete docker container:
#docker rm -f postgres
#command to connect to postgres container: docker exec -it postgres psql -U myuser -d mydb
#docker volume rm <volume_name> : to remove volume created by postgres container
#docker ps -a : to list all container
#docker logs <container_id> : to see logs of a container