services:
  postgres:
    image: postgres:17
    container_name: jobportal
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - D:/JAVA/UDemy/Spring7-SpringBoot4/job-portal-data:/var/lib/postgresql/data